organization: mautic
stickers:
  - id: cm2ejyacj71230ckzd973v0scd
    alias: maintainer
holobytes:
  - evolvingStickerId: cm1ti4x4c57560cjq2styaitm
    icon: avocado
    alias: hacktober-2024
    in: true
